---
# tasks file for kubeconfigs

- name: Distribute kubeadm config to be usedwith kubeadm init --config=
  template:
    src: cluster.kubeconfig.j2
    dest: /home/k8sadmin/.kube/cluster.kubeconfig
    owner: k8sadmin
    group: k8sadmin
  tags:
    - kubeconfig
