---

# Playbook that calls the created roles

- name: call roles
  hosts: all
  become: true
  roles:
  #  - { role: configure_hosts }
  #  - { role: kubeadm_install }
    - { role: nginx_load_balancer , when: inventory_hostname == 192.168.50.117 }
    - { role: certificates , when: inventory_hostname == 192.168.50.113 }
