---

# Playbook that calls the created roles
# nginx_load_balancer only runs on the inventory_hostname of the load balancer host
# certificates only runs on the node you choose to be the CA and distribute certs from

- name: call roles
  hosts: all
  become: true
  roles:
  #  - { role: configure_hosts }
  #  - { role: kubeadm_install }
  #  - { role: nginx_load_balancer , when: inventory_hostname == "192.168.50.117" }
  #  - { role: certificates }
    - { role: kubeconfigs }


