apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-server
  labels:
      app: webserver
      type: front-end
spec:
  template:
    metadata:
      name: nginx-server-pod
      labels:
        app: nginx-server
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3