---
# tasks file for kubeadm_install

# Pre-reqs

- name: open ports ( MASTERS )
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
  with_items:
    - { port: 6443/tcp }
    - { port: 2379-2380/tcp }
    - { port: 10250-10252/tcp }
  when: "'masters' in group_names"

- name: open ports ( WORKERS )
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
  with_items:
    - { port: 10250/tcp }
    - { port: 30000-32767/tcp }
  when: "'workers' in group_names"

- name: Turn on and enable firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: disable swap NOW
  shell: /usr/sbin/swapoff -a

#- name: Disable swap persistently
#  command: sudo sed -i '/ swap / s/^/#/' /etc/fstab

##########################################
## LETTING IPTABLES SEE BRIDGED TRAFFIC ##

- name: Make sure br_netfilter module is loaded
  command: lsmod | grep br_netfilter
  register: netfilter_var
  ignore_errors: true

- name: Load br_netfilter if it is not loaded
  command: /usr/sbin/modprobe br_netfilter
  when: netfilter_var.stdout == ""
  ignore_errors: true

- name: Make sure br_netfilter module is loaded
  command: lsmod | grep overlay
  register: netfilter_var
  ignore_errors: true

- name: Load br_netfilter if it is not loaded
  command: /usr/sbin/modprobe overlay
  when: netfilter_var.stdout == ""
  ignore_errors: true

- name: Place k8s.conf in modules-load.d
  template:
    src: k8s_modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    
- name: Adding /etc/sysctl.d/k8s.conf
  template:
    src: k8s_sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  
- name: Apply sysctl changes
  command: /usr/sbin/sysctl --system

#####################################
## Install software              ####

- name: Install required software to setup containerd install repo
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add docker official gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Setup Stable docker repository
  shell: 'echo \
  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

- name: Apt-get update and Install containerd
  apt:
    pkg:
    - containerd.io
    update_cache: yes

- name: Make /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Set containerd config default
  command: containerd config default | sudo tee /etc/containerd/config.toml

- name: Restart and enable containerd
  service:
    name: containerd
    state: restarted
    enabled: yes

#- name: Install containerd container runtime, kubedadm, kublet, kubectl

#- name: Configure cgroup driver
