---
# tasks file for configure_hosts


# Assign worker nodes hostnames
- name: Assign hostname for worker 01
  hostname:
    name: "{{ k8s-worker-01 }}"
  when: inventory_hostname == {{ worker_address_01 }}

- name: Assign hostname for worker 02
  hostname:
    name: "{{ k8s-worker-02 }}"
  when: inventory_hostname == {{ worker_address_02 }}

- name: Assign hostname for worker 03
  hostname:
    name: "{{ k8s-worker-03 }}"
  when: inventory_hostname == {{ worker_address_03 }}

# Assign API Master Server Hostname
- name: Assign hostname for K8's Master
  hostname:
    name: "{{ k8s-master-01 }}"
  when: inventory_hostname == {{ master_address_01 }}

# Assign Load Balancer Hostname
- name: Assign hostname for Load Balancer
  hostname:
    name: "{{ k8s-balancer-01 }}"
  when: inventory_hostname == {{ balancer_address_01 }}

# Assign NFS/TFTP Server Hostname
- name: Assign hostnames
  hostname:
    name: "{{ management-01 }}"
  when: inventory_hostname == {{ management_address_01 }}
    